packages:
  - 'app/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild

catalog:
  "@types/react": "19.2.5"
  "@types/react-dom": "19.2.3"
  "@types/node": "24.10.1"
  "globals": "16.5.0"
  "react": "19.2.0"
  "react-dom": "19.2.0"
  "typescript": "5.9.3"
  "vite": "npm:rolldown-vite@7.2.5"
  "vitest": "4.0.14"
